name = "reader-service"
main = ".output/server/index.mjs"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "reader-service"
database_id = "2ccea3e6-cd78-45f5-9395-1094f964b273"

[[r2_buckets]]
binding = "ARTICLE_BUCKET"
bucket_name = "reader-articles"

[vars]
AUTH_ORIGIN = "https://reader-service.aiwdm.workers.dev"
